
# ***************************************
# ***Overview***
# Script name: config.py
# Purpose: This script defines the global varialbles for all the scripts
# Project: Connectivity and community impact analysis in Arcpy for potential bicycle infrastructure improvements.
# Extent: 4 PA Counties in Philadelphia suburbs.
# Last updated: May 11, 2019
# Author: Delphine Khanna
# Organization: Bicycle Coalition of Greater Philadelphia
# Note: This Arcpy script is meant to run in ArcGIS Desktop. It is NOT optimized for complete unsupervised automation.
# Commands for the ArcGIS Python interpreter:
#    1. To get into the current directory: import os; os.chdir("C:\Users\delph\Desktop\Github_repos\Connectivity-And-Impact")
#    2. Execute this file: execfile(r'config.py')
# ***************************************

# *********
# Option switches
# Should we remove from the mxd document all intermediary layers generated by the process?
REMOVE_INTERMEDIARY_LAYERS_OPTION = "yes" # or "no"
# We have the option of computing everything from scratch or only recompute the final scores:
COMPUTE_FROM_SCRATCH_OPTION = "yes" # or "yes"

# *********
# Set up global variables used in all scripts (+global variables speficic to roads)
gdb_output_name = "\\script_output_roads3.gdb"
base_path = "C:\\Users\\delph\\Desktop\\GIS\\BCGP\\Connectivity_and_impact"
data_path = base_path + "\\Data"
gdb_CII = data_path + "\\script_output_CII3.gdb"
common_util_path = data_path + "\\common_util.gdb"
gdb_output = data_path + gdb_output_##name
orig_datasets_path = data_path + "\\Orig_datasets"
cii_overall_score_ras = gdb_CII + "\\cii_overall_score_ras"
lts3_orig =  orig_datasets_path + "\\Road_analysis\\DVRPC_Bike_Stress_Suburban_LTS_3_Connections\\DVRPC_Bike_Stress_Suburban_LTS_3_Connections.shp"

county_list = ["Delaware", "Montgomery", "Bucks", "Chester"]

# *********
# Set up global variables for the trail script
##gdb_output_name = "\\script_output_trails3.gdb"
##gdb_output = data_path + gdb_output_name
##islands_orig =  orig_datasets_path + "\\Trail_analysis\\DVRPC_Bike_Stress_LTS_1__2_Islands\\DVRPC_Bike_Stress_LTS_1__2_Islands.shp"
##trails_orig = orig_datasets_path + "\\Trail_analysis\\Non_Circuit_Trails\\Non_Circuit_Trails.kml"
##trails_converted_path = orig_datasets_path + "\\Trail_analysis\\Non_Circuit_Trails"

# *********
# Set up global variables for the CII script
gdb_output_name = "\\script_output_CII3.gdb"
gdb_output = data_path + gdb_output_name
